apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: dns
  namespace: homelab
spec:
  entryPoints:                 
    - dns-udp
  routes:                       
  - match: HostSNI(`*`)         
    services:                  
    - name: homelab-dns         
      port: 53               

