ports:
  websecure:
    tls:
      enabled: true
  postgresql:
    port: 5432
    expose: true
    exposedPort: 5432
    protocol: TCP
  dns-udp:
    port: 53
    expose: true
    exposedPort: 53
    protocol: UDP
  dns-tcp:
    port: 53
    expose: true
    exposedPort: 53
    protocol: TCP
providers:
  kubernetesIngress:
    publishedService:
      enabled: true
  kubernetesCRD:
    allowCrossNamespace: true
    allowExternalNameServices: true