services:
  ytdl_material:
      environment: 
          # ytdl_mongodb_connection_string: 'mongodb://ytdl-mongo-db:27017'
          ytdl_use_local_db: 'true'
          write_ytdl_config: 'true'
      restart: always
      # depends_on:
      #     - ytdl-mongo-db
      volumes:
          - appdata:/app/appdata
          - /mnt/Data/Nextcloud/Data/__groupfolders/1/Audio:/app/audio
          - /mnt/Data/Nextcloud/Data/__groupfolders/1/Video:/app/video
          - subscriptions:/app/subscriptions
          - users:/app/users
      ports:
          - "9998:17442"
      image: tzahi12345/youtubedl-material:latest
  # ytdl-mongo-db:
  #     image: mongo
  #     logging:
  #         driver: "none"          
  #     container_name: mongo-db
  #     restart: always
  #     volumes:
  #         - ./db/:/data/db

volumes:
  appdata:
  subscriptions:
  users:
