apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-certificate
  namespace: traefik
spec:
  secretName: default-certificate
  issuerRef: 
    kind: Issuer
    name: letsencrypt-prod
  commonName: "*.krzwiatrzyk.pl"
  dnsNames:
    - "*.krzwiatrzyk.pl"