apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secretes
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: '1.1.x'
    chart: sealed-secrets
    helm:
      valueFiles:
      - "https://raw.githubusercontent.com/krzwiatrzyk/krzwiatrzyk.pl/main/values/sealed-secrets.yaml"
  destination:
    name: krzwiatrzyk
    namespace: sealed-secrets
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false