# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: traefik
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io/foreground
# spec:
#   project: default
#   source:
#     repoURL: https://helm.traefik.io/traefik
#     targetRevision: '10.x.x'
#     chart: traefik
#     helm:
#       valuesFiles:
#       - "https://raw.githubusercontent.com/krzwiatrzyk/krzwiatrzyk.pl/main/values/traefik.yaml"
#   destination:
#     name: krzwiatrzyk
#     namespace: traefik
#   syncPolicy:
#     automated:
#       prune: false
#       selfHeal: true
#     syncOptions:
#       - PrunePropagationPolicy=foreground
#       - Replace=false
#       - PruneLast=false
#       - Validate=true
#       - CreateNamespace=true
#       - ApplyOutOfSyncOnly=false