apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: '4.20.x'
    chart: kube-state-metrics
    helm:
      values: |
        image:
          tag: v2.4.2
  destination:
    name: krzwiatrzyk
    namespace: grafana-cloud
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false